version: "3"
services:
  javaapp1:     
    image: ahmed3la/osama-1 
    ports:
      - "8080:8080"  
    container_name: javaapp1
  javaapp2:
    image: ahmed3la/salah-1:11
    ports:
      - "7777:8080"
    container_name: javaapp2
  reverse-proxy-11:
    build: ./nginx-container-reverse-proxy 
    ports:
       - "4444:80"
    container_name: reverse-proxy-container
    links:
       - javaapp1
       - javaapp2
